version: "3.7"
services:
  
  presto:
    image: "starburstdata/presto:${PRESTO_VER}"
    env_file:
      - "./.env"
    volumes:
      - "./resources/presto/etc/catalog/hive.properties:${ETC_PRESTO_DIR}/catalog/hive.properties"
      - "./resources/presto/etc/catalog/mysql.properties:${ETC_PRESTO_DIR}/catalog/mysql.properties"
      - "./resources/presto/etc/config.properties:${ETC_PRESTO_DIR}/config.properties"
      - "./resources/presto/etc/jvm.config:${ETC_PRESTO_DIR}/jvm.config"
    container_name: "presto"
    ports:
      - "8080:8080"

  presto-worker:
    image: "starburstdata/presto:${PRESTO_VER}"
    env_file:
      - "./.env"
    volumes:
      - "./resources/presto/etc/catalog/hive.properties:${ETC_PRESTO_DIR}/catalog/hive.properties"
      - "./resources/presto/etc/catalog/mysql.properties:${ETC_PRESTO_DIR}/catalog/mysql.properties"
      - "./resources/presto/etc/config-worker.properties:${ETC_PRESTO_DIR}/config.properties"
      - "./resources/presto/etc/jvm.config:${ETC_PRESTO_DIR}/jvm.config"
    container_name: "presto-worker"
    ports:
      - "8081:8081"
  
  postgres:
    image: "postgres:${POSTGRES_HIVE_HMS_VER}"
    container_name: "postgres"
    env_file:
      - "./.env"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  
  metastore:
    image: "starburstdata/hive-metastore-unsecured:${HMS_UNSECURED_VER}"
    container_name: "metastore"
    depends_on:
      - "postgres"
    env_file:
      - "./.env"
    volumes:
      - "./resources/misc/wait-for-it.sh:/tmp/wait-for-it.sh:ro"
    command: [
      "./tmp/wait-for-it.sh",
      "postgres:5432",
      "--strict",
      "--timeout=60",
      "--",
      "./opt/bin/start-hive-metastore.sh"
      ]
    ports:
      - "9083:9083"
  
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - './resources/minio/data/:/data'
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    command: server /data

volumes:
  postgres-data:
